charityfinder_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('charityfinder/', include('charityfinder_app.urls')),
    path('accounts/', include('login_app.urls')),
    # api interface login/out option
    path('api-auth/', include('rest_framework.urls')),
    # all-auth, alt to using custom login app
    # path('accounts/', include('allauth.urls')),
    path('comments/', include('comment_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment_app/urls.py
from django.urls import path
from . import views

app_name = 'comment_app'

urlpatterns = [
    # path('projects/<int:pid>/comments', views.project_comments, name='project_comments'),
    path('projects/<int:pid>/new-comment', views.new_comment, name='new_comment'),
    path('projects/<int:pid>/delete-comment', views.delete_comment, name='delete_comment'),
    path('projects/<int:pid>/new-comment-rating', views.new_comment_rating, name='new_rating'),
]

login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('request_password_reset/', views.request_password_reset, name='request_password_reset'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('delete_account/', views.delete_account, name='delete_account'),
]

comment_app/models.py
from django.db import models
from django.contrib.auth.models import User
from mptt.models import MPTTModel, TreeForeignKey
# pluralize used to add 's' when appropriate
from django.template.defaultfilters import pluralize
from datetime import timedelta
from django.utils import timezone


class Comment(MPTTModel):
    # 8 = deleted user instance
    author = models.ForeignKey(User, on_delete=models.SET(8))
    body = models.CharField(max_length=2000)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # indexed for faster queries on individual project endpoints
    project_id = models.IntegerField(db_index=True)
    # rated = models.ManyToManyField(User, through='UserCommentRating', related_name='rated_user')
    # null = required by MPTT model, comment not deleted, but updated to "deleted" to keep structure
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    def __str__(self):
        return f"{self.author} - {self.created}"

    class MPTTMeta:
        # Category.objects.rebuild() to apply to existing structure
        order_insertion_by = ['-created']

    def comment_age(self):
        age = timezone.now() - self.created
        if age < timedelta(minutes=1):
            return f"{age.seconds} second{pluralize(age.seconds)} ago"
        elif age < timedelta(hours=1):
            # only tracks seconds
            # total_seconds returns a float
            minutes = int(age.total_seconds()) // 60
            return f"{minutes} minute{pluralize(minutes)} ago"
        elif age < timedelta(days=1):
            hours = int(age.total_seconds()) // 3600
            return f"{hours} hour{pluralize(hours)} ago"
        else:
            return f"{age.days} day{pluralize(age.days)} ago"

    def comment_calculated_rating(self):
        ups = UserCommentRating.objects.filter(comment=self.pk, state='1').count()
        downs = UserCommentRating.objects.filter(comment=self.pk, state='-1').count()
        return ups - downs


class UserCommentRating(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET(8))
    state = models.CharField(max_length=2)

comment_app/views.py
from django.shortcuts import redirect, get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from .models import Comment, UserCommentRating


def project_comments(request, pid):
    comments = Comment.objects.filter(project_id=pid)  # .order_by('-rated', '-created')

    context = {
        'pid': pid,
        'comments': comments,
    }
    return render(request, 'comment_app/comments.html', context)


@login_required  # alt: request.user.is_authenticated check
def new_comment(request, pid):
    if request.method == 'POST':
        text = request.POST['newComment']
        comment = Comment()
        comment.body = text
        comment.author = request.user
        comment.project_id = pid
        if "reply" in request.POST:
            comment.parent = Comment.objects.get(pk=request.POST['reply'])
        comment.save()
        print('comment saved')
        return redirect(reverse('charityfinder_app:project', args={pid}))
    else:
        print('not authorized to comment')


@login_required
def new_comment_rating(request, pid):
    if request.method == 'POST':
        # "defaults" only execute when create, created = boolean
        # also protects against race conditions
        rated, created = UserCommentRating.objects.get_or_create(
            user=request.user,
            comment=Comment.objects.get(pk=request.POST['reply']),
            defaults={'state': request.POST['comment_rating']},
        )
        if not created:
            rated.state = request.POST['comment_rating']
            rated.save()
            print('comment rating updated')
        else:
            print('comment rating created')
        return redirect(reverse('charityfinder_app:project', args={pid}))
    else:
        print('not authorized to vote')


@login_required
def delete_comment(request, pid):
    if request.method == 'POST':
        comment = get_object_or_404(Comment, author=request.user, pk=request.POST['reply'])
        comment.body = 'Deleted'
        comment.save()
        print('comment deleted')
        return redirect(reverse('charityfinder_app:project', args={pid}))
    else:
        print('not authorized to delete')

comment_app/templates/comment_app/comments.html
{% extends "charityfinder_app/base.html" %}

{% block comment %}
<section id="comment-section" class="content">
{# comment interactions, eventually made with ajax, components etc. #}
    <div id="post-comment-container">
        {% if request.user.is_authenticated %}
           <form action="{% url 'comment_app:new_comment' pid %}" method="POST">
                <textarea
                        class="comment-input-style-1"
                        name="newComment"
                        placeholder="Comment on this project"></textarea>
                <br />
                <button class="btn-style-2">Post</button>
                {% csrf_token %}
            </form>
        {% else %}
            <input type="text" name="newComment" placeholder="Login to comment" disabled/>
        {% endif %}
    </div>

    {% load mptt_tags %}
    <ul>
        {% recursetree comments %}
            <div class="bg-style-1">
                <div id="comment-panel">
                    <div>{{ node.author }}</div>
                    <div class="small-left-gap">{{ node.comment_age }}</div>
                    <div class="small-left-gap">{{ node.comment_calculated_rating }} point</div>
                    {% if request.user.is_authenticated %}
                        <form action="{% url 'comment_app:new_rating' pid %}" method="POST">
                            {% csrf_token %}
                            <button class="btn-style-3" onclick="
                                this.parentElement.lastElementChild.setAttribute('value', '1');">⬆️
                            </button>
                            <button class="btn-style-3" onclick="
                                this.parentElement.lastElementChild.setAttribute('value', '-1');">⬇️
                            </button>
                            <button class="btn-style-3" onclick="
                                this.parentElement.lastElementChild.setAttribute('value', '0');">❎
                            </button>
                            {% if request.user == node.author %}
                                <button
                                        formaction="{% url 'comment_app:delete_comment' pid %}"
                                        class="btn-style-4">Delete
                                </button>
                            {% endif %}
                            <input type="hidden" name="reply" value="{{ node.pk }}" />
                            <input type="hidden" name="comment_rating" value="" />
                        </form>
                    {% endif %}
                </div>
                <div class="comment-box-style-1"><p class="text-style-1">{{ node.body }}</p></div>
                {% if request.user.is_authenticated %}
                    <button
                            id="reply-btn" class="btn-style-1"
                            onclick="this.nextElementSibling.setAttribute('style', 'display: Inherit;')">↩️
                    </button>
                    <form
                            action="{% url 'comment_app:new_comment' pid %}"
                            method="POST" style="display:none" id="reply-form-{{ node.pk }}">
                        <textarea
                                class="comment-input-style-1 "
                                name="newComment"
                                placeholder="Write a reply"></textarea>
                        <input type="hidden" name="reply" value="{{ node.pk }}" />
                        <br />
                        <button class="btn-style-2">Post</button>
                        {% csrf_token %}
                    </form>
                {% endif %}
            </div>

            {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                </ul>
            {% endif %}
        {% endrecursetree %}
    </ul>
</section>
{% endblock %}