charityfinder_app/urls.py
from django.urls import path, include
from .api import CommentList, CommentDetail, UserList, UserDetail
from . import views, api

app_name = 'charityfinder_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('projects/<int:pid>/', views.project_detail, name='project'),
    path('projects/<int:pid>/new-vote', views.new_project_vote, name='new_vote'),

    # API
    path('api/v1/comments/', CommentList.as_view()),
    path('api/v1/comments/<int:pk>/', CommentDetail.as_view()),
    path('api/v1/users/', UserList.as_view()),
    path('api/v1/users/<int:pk>/', UserDetail.as_view()),
    path('api/v1/projects/<int:pid>/', api.project_detail),
    path('api/v1/projects/', api.project_list),
    # django-rest-auth provided endpoints, integrated token handling, validation etc.
    path('api/v1/rest-auth/', include('rest_auth.urls')),
    path('api/v1/rest-auth/signup/', include('rest_auth.registration.urls')),
]

charityfinder_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('charityfinder/', include('charityfinder_app.urls')),
    path('accounts/', include('login_app.urls')),
    # api interface login/out option
    path('api-auth/', include('rest_framework.urls')),
    # all-auth, alt to using custom login app
    # path('accounts/', include('allauth.urls')),
    path('comments/', include('comment_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('request_password_reset/', views.request_password_reset, name='request_password_reset'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('delete_account/', views.delete_account, name='delete_account'),
]

charityfinder_app/models.py
from django.db import models
from django.db.models import Avg
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator


class UserProjectRating(models.Model):
    project_id = models.IntegerField(db_index=True)
    user = models.ForeignKey(User, on_delete=models.SET(8))
    rating = models.PositiveSmallIntegerField(validators=[MaxValueValidator(10)])


def project_calculated_rating(pid):
    project_list = UserProjectRating.objects.filter(project_id=pid)
    avg = project_list.aggregate(Avg('rating'))['rating__avg']
    return avg

charityfinder_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core.cache import cache
from .gg_api_call import gg_call_project

from .models import UserProjectRating, project_calculated_rating
from comment_app .models import Comment


def index(request):
    return render(request, 'charityfinder_app/index.html')


def project_detail(request, pid):
    query = 'https://api.globalgiving.org/api/public/projectservice/projects/'
    gg_call_project(pid, query)

    comments = Comment.objects.filter(project_id=pid)
    project_rating = project_calculated_rating(pid)

    context = {
        'gg_api_data': cache.get(f"project_{pid}"),
        'pid': pid,
        'comments': comments,
        'project_rating': project_rating
    }
    return render(request, 'charityfinder_app/project.html', context)


@login_required
def new_project_vote(request, pid):
    if request.method == 'POST':
        rated, created = UserProjectRating.objects.get_or_create(
            user=request.user,
            project_id=pid,
            defaults={'rating': request.POST['project_rating']},
        )
        if not created:
            rated.rating = request.POST['project_rating']
            rated.save()
            print('project rating updated')
        else:
            print('project rating created')
        return redirect(reverse('charityfinder_app:project', args={pid}))
    else:
        print('not authorized to vote')

charityfinder_app/templates/charityfinder_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'charityfinder_app/style.css' %}" media="screen"/>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <title>Chariftyfinder</title>
</head>
<body>
    <nav>
        <img src="/media/Charityfinder_logo4.png" height="50em" id="nav-logo" alt="logo">
        <a href="#">Home</a>
        <a href="#">About</a>
        <a href="#">Stuff</a>
        <a href="#">Things</a>
        {% if request.user.is_authenticated %}
            <div><p id="acc">Logged in: <strong>{{ user }}</strong> - <a href="{% url 'login_app:logout' %}">Log out</a></p></div>
        {% else %}
            <p id="acc"><a href="{% url 'login_app:login' %}">Log in</a></p>
        {% endif %}
    </nav>
    {% block content %}
    {% endblock %}
    {% block charity %}
    {% endblock %}
    {% block comment %}
    {% endblock %}
</body>
</html>

charityfinder_app/templates/charityfinder_app/index.html
{% extends "charityfinder_app/base.html" %}

{% block content %}

<section id="index-section">
    <div id="search-area">
        <div id="hero-img"></div>
        <h2 id="hero-text">Strive for a better world</h2>
       <input type="text" placeholder="Search charity projects">
    </div>

    <div>
        <h1 class="headline">Explore charities</h1>
    </div>
</section>

{% endblock %}

charityfinder_app/templates/charityfinder_app/project.html
{% extends "comment_app/comments.html" %}

{% block charity %}
<section class="content">
    <h1>{{ gg_api_data.project.title }}</h1>
    {# accessing last element using |last #}
    {# accessing key/value using %with/as% assignment #}
    <div id="project-img-container">
        <img id="project-img" src="
            {% with gg_api_data.project.image.imagelink|last as last %}
                {{ last.url }}
            {% endwith %}" />
    </div>
    <p>{{ gg_api_data.project.summary }}</p>
    <p>Country:
         {% for country in gg_api_data.project.countries.country %}
            <strong>{{ country.name }}</strong>
         {% endfor %}</p>
    <p>Themes:
        {% for theme in gg_api_data.project.themes.theme %}
            <strong>{{ theme.name }}</strong>
        {% endfor %}</p>
    <p>Donation options:</p>
        {% for option in gg_api_data.project.donationOptions.donationOption %}
            <p><strong>{{ option.amount }}</strong> - {{ option.description }}</p>
        {% endfor %}
    <p>Organization: <strong>{{ gg_api_data.project.organization.name }}</strong></p>
    <p>Website: <a href="{{ gg_api_data.project.organization.url }}">{{ gg_api_data.project.organization.url }}</a></p>
    <p>Mission:</p> <p>{{ gg_api_data.project.organization.mission }}</p>
    <p id="org-rating">Organization rated by users:
        <strong>{{ project_rating|floatformat:1 }}</strong>
        <span style="font-size: 0.9em">⭐</span>
    </p>
    <div><p>Rate org:</p>
        {% if request.user.is_authenticated %}
            <form action="{% url 'charityfinder_app:new_vote' pid %}" method="POST">
                {% csrf_token %}
                <div id="slidecontainer">
                    <input type="range" min="0" max="10" value="10" name="project_rating" id="rating-slider">
                    <strong><span id="slider-value"></span></strong>
                    <button class="btn-style-3">Rate</button>
                </div>
            </form>
        {% endif %}
    </div>
</section>
<script>
    const slider = document.getElementById("rating-slider");
    const slider_output = document.getElementById("slider-value");
    slider_output.innerHTML = slider.value;

    slider.oninput = function() {
      slider_output.innerHTML = this.value;
    }
</script>
{% endblock %}